"""Assemble compiled block fragments into one self-contained artifact (design §5 ④).

P0 supports the ``html`` target: a single .html file with inline CSS/JS and no
external runtime deps (design §3.1 #5). The ``.kl-*`` design tokens give all
blocks a consistent look; LLM-generated blocks are told to reuse them.
"""

from __future__ import annotations

import html as _html
from typing import List

from .schema import KnowlingSpec

_CSS = """
:root {
  --kl-bg: #ffffff; --kl-fg: #1f2328; --kl-muted: #57606a;
  --kl-accent: #3056d3; --kl-accent-2: #e8590c;
  --kl-border: #d0d7de; --kl-soft: #f6f8fa; --kl-radius: 10px;
  --kl-ok: #1a7f37; --kl-bad: #cf222e;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--kl-soft); color: var(--kl-fg);
  font: 16px/1.65 -apple-system, "Segoe UI", "PingFang SC", "Hiragino Sans GB", sans-serif;
}
.kl-doc { max-width: 760px; margin: 0 auto; padding: 32px 20px 80px; }
.kl-header { margin-bottom: 24px; }
.kl-header h1 { font-size: 28px; margin: 0 0 6px; }
.kl-hook { color: var(--kl-muted); font-size: 15px; margin: 0; }
.kl-block {
  background: var(--kl-bg); border: 1px solid var(--kl-border);
  border-radius: var(--kl-radius); padding: 20px 22px; margin: 18px 0;
}
.kl-block h2, .kl-block h3 { margin-top: 0; }
.kl-block code { background: var(--kl-soft); padding: 1px 5px; border-radius: 5px; font-size: .9em; }
/* quiz */
.kl-quiz-q { font-weight: 600; }
.kl-quiz-opts { display: flex; flex-direction: column; gap: 8px; margin: 12px 0; }
.kl-quiz-opt {
  text-align: left; padding: 10px 14px; border: 1px solid var(--kl-border);
  border-radius: 8px; background: var(--kl-bg); cursor: pointer; font: inherit;
  transition: background .15s, border-color .15s;
}
.kl-quiz-opt:hover { background: var(--kl-soft); }
.kl-quiz-opt.is-correct { border-color: var(--kl-ok); background: #e6f6ea; }
.kl-quiz-opt.is-wrong { border-color: var(--kl-bad); background: #fde8e8; }
.kl-quiz-feedback { margin: 4px 0 0; font-size: 14px; }
.kl-quiz-feedback.is-correct { color: var(--kl-ok); }
.kl-quiz-feedback.is-wrong { color: var(--kl-bad); }
/* param_sim */
.kl-ps-controls { display: flex; flex-direction: column; gap: 12px; }
.kl-ps-ctl { display: grid; grid-template-columns: 120px 1fr 64px; align-items: center; gap: 12px; }
.kl-ps-name { font-size: 14px; color: var(--kl-muted); }
.kl-ps-ctl input[type=range] { width: 100%; accent-color: var(--kl-accent); }
.kl-ps-val { font-variant-numeric: tabular-nums; text-align: right; font-weight: 600; }
.kl-ps-outputs { display: flex; flex-wrap: wrap; gap: 16px; margin: 16px 0; }
.kl-ps-out { background: var(--kl-soft); border-radius: 8px; padding: 8px 14px; }
.kl-ps-out span { color: var(--kl-muted); font-size: 13px; margin-right: 8px; }
.kl-ps-out strong { font-variant-numeric: tabular-nums; color: var(--kl-accent); }
.kl-ps-canvas { width: 100%; height: auto; background: var(--kl-bg); border: 1px solid var(--kl-border); border-radius: 8px; }
.kl-ps-explain { color: var(--kl-muted); font-size: 14px; }
/* generic fallback */
.kl-generic-tag { color: var(--kl-accent-2); font-size: 14px; }
.kl-generic pre { background: var(--kl-soft); padding: 12px; border-radius: 8px; overflow: auto; font-size: 13px; }
.kl-footer { margin-top: 32px; color: var(--kl-muted); font-size: 12px; text-align: center; }
"""


def assemble_html(spec: KnowlingSpec, fragments: List[str], title: str) -> str:
    hook = spec.pedagogy.hook if spec.pedagogy else ""
    body = "\n".join(fragments)
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_html.escape(title)} · Knowling</title>
<style>{_CSS}</style>
</head>
<body>
<main class="kl-doc">
  <header class="kl-header">
    <h1>{_html.escape(title)}</h1>
    {f'<p class="kl-hook">{_html.escape(hook)}</p>' if hook else ''}
  </header>
{body}
  <footer class="kl-footer">Generated by Knowling · 自包含交互学习组件</footer>
</main>
</body>
</html>"""
